# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: douyin_user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='douyin_user.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64ouyin_user.proto\x12\x08tutorial\";\n\nDouYinUser\x12\x1c\n\x04user\x18\x02 \x01(\x0b\x32\x0e.tutorial.User\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\xd3\x05\n\x04User\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x10\n\x08short_id\x18\x02 \x01(\x03\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\x05\x12*\n\thead_info\x18\t \x01(\x0b\x32\x17.tutorial.User.HeadInfo\x12+\n\tlevelInfo\x18\x15 \x01(\x0b\x32\x18.tutorial.User.LevelInfo\x12)\n\x08userInfo\x18\x16 \x01(\x0b\x32\x17.tutorial.User.UserInfo\x12/\n\x0blevelDetail\x18\x17 \x01(\x0b\x32\x1a.tutorial.User.LevelDetail\x12\r\n\x05\x64y_id\x18& \x01(\t\x12\x0f\n\x07sec_uid\x18. \x01(\t\x1a\x1b\n\x08HeadInfo\x12\x0f\n\x07headImg\x18\x01 \x03(\t\x1a\xad\x01\n\tLevelInfo\x12\x10\n\x08levelImg\x18\x01 \x03(\t\x12\x12\n\nlevel_type\x18\x02 \x01(\t\x12;\n\x0c\x66\x61nsCardInfo\x18\x08 \x01(\x0b\x32%.tutorial.User.LevelInfo.FansCardInfo\x1a=\n\x0c\x46\x61nsCardInfo\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x05\x1a\x1f\n\x0bLevelDetail\x12\x10\n\x08levelNum\x18\x06 \x01(\x05\x1a\x95\x01\n\x0c\x46\x61nsCardInfo\x12\x14\n\x0c\x66\x61nsLevelImg\x18\x01 \x03(\t\x12\x36\n\ncardFormat\x18\x08 \x01(\x0b\x32\".tutorial.User.FansCardInfo.format\x1a\x37\n\x06\x66ormat\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x05\x1a/\n\x08UserInfo\x12\x12\n\nfollowNums\x18\x01 \x01(\x05\x12\x0f\n\x07\x66\x61nsNum\x18\x02 \x01(\x05\x62\x06proto3'
)




_DOUYINUSER = _descriptor.Descriptor(
  name='DouYinUser',
  full_name='tutorial.DouYinUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='tutorial.DouYinUser.user', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.DouYinUser.content', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=90,
)


_USER_HEADINFO = _descriptor.Descriptor(
  name='HeadInfo',
  full_name='tutorial.User.HeadInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='headImg', full_name='tutorial.User.HeadInfo.headImg', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=406,
)

_USER_LEVELINFO_FANSCARDINFO = _descriptor.Descriptor(
  name='FansCardInfo',
  full_name='tutorial.User.LevelInfo.FansCardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.User.LevelInfo.FansCardInfo.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='tutorial.User.LevelInfo.FansCardInfo.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='tutorial.User.LevelInfo.FansCardInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=582,
)

_USER_LEVELINFO = _descriptor.Descriptor(
  name='LevelInfo',
  full_name='tutorial.User.LevelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='levelImg', full_name='tutorial.User.LevelInfo.levelImg', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level_type', full_name='tutorial.User.LevelInfo.level_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fansCardInfo', full_name='tutorial.User.LevelInfo.fansCardInfo', index=2,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USER_LEVELINFO_FANSCARDINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=582,
)

_USER_LEVELDETAIL = _descriptor.Descriptor(
  name='LevelDetail',
  full_name='tutorial.User.LevelDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='levelNum', full_name='tutorial.User.LevelDetail.levelNum', index=0,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=615,
)

_USER_FANSCARDINFO_FORMAT = _descriptor.Descriptor(
  name='format',
  full_name='tutorial.User.FansCardInfo.format',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.User.FansCardInfo.format.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='tutorial.User.FansCardInfo.format.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='tutorial.User.FansCardInfo.format.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=767,
)

_USER_FANSCARDINFO = _descriptor.Descriptor(
  name='FansCardInfo',
  full_name='tutorial.User.FansCardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fansLevelImg', full_name='tutorial.User.FansCardInfo.fansLevelImg', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cardFormat', full_name='tutorial.User.FansCardInfo.cardFormat', index=1,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USER_FANSCARDINFO_FORMAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=767,
)

_USER_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='tutorial.User.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='followNums', full_name='tutorial.User.UserInfo.followNums', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fansNum', full_name='tutorial.User.UserInfo.fansNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=816,
)

_USER = _descriptor.Descriptor(
  name='User',
  full_name='tutorial.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='tutorial.User.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='short_id', full_name='tutorial.User.short_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='tutorial.User.nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='tutorial.User.gender', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='head_info', full_name='tutorial.User.head_info', index=4,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='levelInfo', full_name='tutorial.User.levelInfo', index=5,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='tutorial.User.userInfo', index=6,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='levelDetail', full_name='tutorial.User.levelDetail', index=7,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dy_id', full_name='tutorial.User.dy_id', index=8,
      number=38, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec_uid', full_name='tutorial.User.sec_uid', index=9,
      number=46, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USER_HEADINFO, _USER_LEVELINFO, _USER_LEVELDETAIL, _USER_FANSCARDINFO, _USER_USERINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=816,
)

_DOUYINUSER.fields_by_name['user'].message_type = _USER
_USER_HEADINFO.containing_type = _USER
_USER_LEVELINFO_FANSCARDINFO.containing_type = _USER_LEVELINFO
_USER_LEVELINFO.fields_by_name['fansCardInfo'].message_type = _USER_LEVELINFO_FANSCARDINFO
_USER_LEVELINFO.containing_type = _USER
_USER_LEVELDETAIL.containing_type = _USER
_USER_FANSCARDINFO_FORMAT.containing_type = _USER_FANSCARDINFO
_USER_FANSCARDINFO.fields_by_name['cardFormat'].message_type = _USER_FANSCARDINFO_FORMAT
_USER_FANSCARDINFO.containing_type = _USER
_USER_USERINFO.containing_type = _USER
_USER.fields_by_name['head_info'].message_type = _USER_HEADINFO
_USER.fields_by_name['levelInfo'].message_type = _USER_LEVELINFO
_USER.fields_by_name['userInfo'].message_type = _USER_USERINFO
_USER.fields_by_name['levelDetail'].message_type = _USER_LEVELDETAIL
DESCRIPTOR.message_types_by_name['DouYinUser'] = _DOUYINUSER
DESCRIPTOR.message_types_by_name['User'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DouYinUser = _reflection.GeneratedProtocolMessageType('DouYinUser', (_message.Message,), {
  'DESCRIPTOR' : _DOUYINUSER,
  '__module__' : 'douyin_user_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.DouYinUser)
  })
_sym_db.RegisterMessage(DouYinUser)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {

  'HeadInfo' : _reflection.GeneratedProtocolMessageType('HeadInfo', (_message.Message,), {
    'DESCRIPTOR' : _USER_HEADINFO,
    '__module__' : 'douyin_user_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.User.HeadInfo)
    })
  ,

  'LevelInfo' : _reflection.GeneratedProtocolMessageType('LevelInfo', (_message.Message,), {

    'FansCardInfo' : _reflection.GeneratedProtocolMessageType('FansCardInfo', (_message.Message,), {
      'DESCRIPTOR' : _USER_LEVELINFO_FANSCARDINFO,
      '__module__' : 'douyin_user_pb2'
      # @@protoc_insertion_point(class_scope:tutorial.User.LevelInfo.FansCardInfo)
      })
    ,
    'DESCRIPTOR' : _USER_LEVELINFO,
    '__module__' : 'douyin_user_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.User.LevelInfo)
    })
  ,

  'LevelDetail' : _reflection.GeneratedProtocolMessageType('LevelDetail', (_message.Message,), {
    'DESCRIPTOR' : _USER_LEVELDETAIL,
    '__module__' : 'douyin_user_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.User.LevelDetail)
    })
  ,

  'FansCardInfo' : _reflection.GeneratedProtocolMessageType('FansCardInfo', (_message.Message,), {

    'format' : _reflection.GeneratedProtocolMessageType('format', (_message.Message,), {
      'DESCRIPTOR' : _USER_FANSCARDINFO_FORMAT,
      '__module__' : 'douyin_user_pb2'
      # @@protoc_insertion_point(class_scope:tutorial.User.FansCardInfo.format)
      })
    ,
    'DESCRIPTOR' : _USER_FANSCARDINFO,
    '__module__' : 'douyin_user_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.User.FansCardInfo)
    })
  ,

  'UserInfo' : _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
    'DESCRIPTOR' : _USER_USERINFO,
    '__module__' : 'douyin_user_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.User.UserInfo)
    })
  ,
  'DESCRIPTOR' : _USER,
  '__module__' : 'douyin_user_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.User)
  })
_sym_db.RegisterMessage(User)
_sym_db.RegisterMessage(User.HeadInfo)
_sym_db.RegisterMessage(User.LevelInfo)
_sym_db.RegisterMessage(User.LevelInfo.FansCardInfo)
_sym_db.RegisterMessage(User.LevelDetail)
_sym_db.RegisterMessage(User.FansCardInfo)
_sym_db.RegisterMessage(User.FansCardInfo.format)
_sym_db.RegisterMessage(User.UserInfo)


# @@protoc_insertion_point(module_scope)
