# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebcastLiveEcomMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WebcastLiveEcomMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cWebcastLiveEcomMessage.proto\"\xfc\x01\n\x16WebcastLiveEcomMessage\x12<\n\x0elive_ecom_desc\x18\x01 \x01(\x0b\x32$.WebcastLiveEcomMessage.LiveEcomDesc\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bpeople_nums\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x1a\n\x12shopping_cart_icon\x18\x06 \x01(\t\x1aT\n\x0cLiveEcomDesc\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x11\n\tmessageId\x18\x02 \x01(\x03\x12\x0e\n\x06roomId\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x62\x06proto3'
)




_WEBCASTLIVEECOMMESSAGE_LIVEECOMDESC = _descriptor.Descriptor(
  name='LiveEcomDesc',
  full_name='WebcastLiveEcomMessage.LiveEcomDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='WebcastLiveEcomMessage.LiveEcomDesc.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='messageId', full_name='WebcastLiveEcomMessage.LiveEcomDesc.messageId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='WebcastLiveEcomMessage.LiveEcomDesc.roomId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='WebcastLiveEcomMessage.LiveEcomDesc.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=285,
)

_WEBCASTLIVEECOMMESSAGE = _descriptor.Descriptor(
  name='WebcastLiveEcomMessage',
  full_name='WebcastLiveEcomMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='live_ecom_desc', full_name='WebcastLiveEcomMessage.live_ecom_desc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='WebcastLiveEcomMessage.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='people_nums', full_name='WebcastLiveEcomMessage.people_nums', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='WebcastLiveEcomMessage.content', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shopping_cart_icon', full_name='WebcastLiveEcomMessage.shopping_cart_icon', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WEBCASTLIVEECOMMESSAGE_LIVEECOMDESC, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=285,
)

_WEBCASTLIVEECOMMESSAGE_LIVEECOMDESC.containing_type = _WEBCASTLIVEECOMMESSAGE
_WEBCASTLIVEECOMMESSAGE.fields_by_name['live_ecom_desc'].message_type = _WEBCASTLIVEECOMMESSAGE_LIVEECOMDESC
DESCRIPTOR.message_types_by_name['WebcastLiveEcomMessage'] = _WEBCASTLIVEECOMMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebcastLiveEcomMessage = _reflection.GeneratedProtocolMessageType('WebcastLiveEcomMessage', (_message.Message,), {

  'LiveEcomDesc' : _reflection.GeneratedProtocolMessageType('LiveEcomDesc', (_message.Message,), {
    'DESCRIPTOR' : _WEBCASTLIVEECOMMESSAGE_LIVEECOMDESC,
    '__module__' : 'WebcastLiveEcomMessage_pb2'
    # @@protoc_insertion_point(class_scope:WebcastLiveEcomMessage.LiveEcomDesc)
    })
  ,
  'DESCRIPTOR' : _WEBCASTLIVEECOMMESSAGE,
  '__module__' : 'WebcastLiveEcomMessage_pb2'
  # @@protoc_insertion_point(class_scope:WebcastLiveEcomMessage)
  })
_sym_db.RegisterMessage(WebcastLiveEcomMessage)
_sym_db.RegisterMessage(WebcastLiveEcomMessage.LiveEcomDesc)


# @@protoc_insertion_point(module_scope)
